### ISSUE TITLE
Random extremely high jumps

### ISSUE THREAD

**Issue by potocpav** [morgenthum/lambda-heights#3]
Demo: [20190617212332.zip](https://github.com/morgenthum/lambda-heights/files/3298903/20190617212332.zip)

This replay shows a 600-score jump that I semi-randomly got. Smaller jumps (~score 80) are much more frequent, but it is hard to say whether those are an intended mechanic or not. I was holding "w" and "d" for the duration of the jump.

**Comment by morgenthum** [comment]
I tried it and found the bug. Currently I don't check if the key-pressed event is repeating. The input handler should stop triggering the jump if it's a repeating event. Currently you get the jump-boost every frame you are flying through a layer while pressing the space key. I'm going to fix it today evening. Thank you! :)

**Comment by potocpav** [comment]
I figured it would be something like that. Btw. good job with the game! I already spent more time playing than I reasonably should have  :)

**Comment by morgenthum** [comment]
Thank you! I fixed it with the recent commit.
